music_app/music_app/album/urls.py
from django.urls import path, include

from music_app.album.views import AlbumAddView, AlbumDetailView, AlbumEditView, AlbumDeleteView

urlpatterns = (
    path('add/', AlbumAddView.as_view(), name='add-album'),
    path('<int:pk>/', include([
        path('details/', AlbumDetailView.as_view(), name='details-album'),
        path('edit/', AlbumEditView.as_view(), name='edit-album'),
        path('delete/', AlbumDeleteView.as_view(), name='delete-album'),

    ])),
)

music_app/music_app/profiles/urls.py
from django.urls import path

from music_app.profiles.views import ProfileDetailsView, ProfileDeleteView

urlpatterns = (
    path('details/', ProfileDetailsView.as_view(), name='profile-details'),
    path('delete/', ProfileDeleteView.as_view(), name='profile-delete'),
)

music_app/music_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("music_app.web.urls")),
    path('album/', include("music_app.album.urls")),
    path('profile/', include("music_app.profiles.urls")),

]

music_app/music_app/web/urls.py
from django.urls import path

from music_app.web.views import index, create_profile

urlpatterns = (
    path("", index, name="index"),
    path("create_profile", create_profile, name="create_profile"),
)

music_app/music_app/album/models.py
from django.core.validators import MinValueValidator
from django.db import models

from music_app.profiles.models import Profile


class Genre(models.TextChoices):
    POP_MUSIC = "Pop Music"
    JAZZ_MUSIC = "Jazz Music"
    RNB_MUSIC = "R&B Music"
    ROCK_MUSIC = "Rock Music"
    COUNTRY_MUSIC = "Country Music"
    DANCE_MUSIC = "Dance Music"
    HIP_HOP_MUSIC = "Hip Hop Music"
    OTHER = "Other"


# Create your models here.
class Album(models.Model):
    MAX_ALBUM_NAME_LENGTH = 30
    MAX_ARTIST_LENGTH = 30
    MAX_GENRE_LENGTH = 30

    album_name = models.CharField(
        max_length=MAX_ALBUM_NAME_LENGTH,
        unique=True,
    )

    artist = models.CharField(
        max_length=MAX_ARTIST_LENGTH,
    )

    genre = models.CharField(
        max_length=MAX_GENRE_LENGTH,
        choices=Genre.choices
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField(
        null=True,
        blank=True,
    )

    price = models.FloatField(
        validators=[MinValueValidator(0.0)]
    )

    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
    )

music_app/music_app/profiles/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


# Create your models here.
class Profile(models.Model):
    MAX_LENGTH_USERNAME = 15
    MIN_LENGTH_USERNAME = 2
    username = models.CharField(
        max_length=MAX_LENGTH_USERNAME,
        validators=[
            MinLengthValidator(MIN_LENGTH_USERNAME),
            RegexValidator(
                regex=r"^[\w]+$",
                message="Ensure this value contains only letters, numbers, and underscore.",

            )], )
    email = models.EmailField()
    age = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

music_app/music_app/web/models.py
from django.db import models

# Create your models here.

music_app/music_app/web/forms.py
from django import forms

from music_app.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:

        model = Profile
        fields = "__all__"
        # fields = ("username", "email", "age")

        widgets = {
            "username": forms.TextInput(attrs={'placeholder': 'Username'}),
            "email": forms.EmailInput(attrs={'placeholder': 'Email'}),
            "age": forms.NumberInput(attrs={'placeholder': 'Age'}),
        }

music_app/music_app/album/views.py
from django import forms
from django.forms import modelform_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from music_app.album.models import Album
from music_app.profiles.models import Profile


# Create your views here.

class AlbumFieldsMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["album_name"].widget.attrs = {"placeholder": "Album Name"}
        form.fields["artist"].widget.attrs = {"placeholder": "Artist"}
        form.fields["description"].widget.attrs = {"placeholder": "Description"}
        form.fields["image_url"].widget.attrs = {"placeholder": "Image URL"}
        form.fields['price'].widget = forms.TextInput(attrs={'placeholder': 'Price'})
        return form


class AlbumAddView(AlbumFieldsMixin, views.CreateView):
    queryset = Album.objects.all()
    fields = ("album_name", "artist", "genre", "description", "image_url", "price")
    template_name = "album/album-add.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        form.instance.owner_id = Profile.objects.first().pk
        return super().form_valid(form)


class AlbumDetailView(AlbumFieldsMixin, views.DetailView):
    queryset = Album.objects.all()
    fields = ("album_name", "artist", "genre", "description", "image_url", "price")
    template_name = "album/album-details.html"


class AlbumEditView(AlbumFieldsMixin, views.UpdateView):
    queryset = Album.objects.all()
    fields = ("album_name", "artist", "genre", "description", "image_url", "price")
    template_name = "album/album-edit.html"
    success_url = reverse_lazy("index")


class AlbumDeleteView(views.DeleteView):
    queryset = Album.objects.all()
    form_class = modelform_factory(
        model=Album,
        fields=("album_name", "artist", "genre", "description", "image_url", "price"),
    )
    template_name = "album/album-delete.html"
    success_url = reverse_lazy("index")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        for field in form.fields.values():
            field.widget.attrs["readonly"] = "readonly"
        return form

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs

music_app/music_app/profiles/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic as views

from music_app.profiles.models import Profile


# Create your views here.
class ProfileObjectMixin:
    def get_object(self, queryset=None):
        return Profile.objects.first()


class ProfileDetailsView(ProfileObjectMixin,views.DetailView):
    template_name = "profile/profile-details.html"


class ProfileDeleteView(ProfileObjectMixin,views.DeleteView):
    template_name = "profile/profile-delete.html"
    success_url = reverse_lazy("index")

music_app/music_app/web/views.py
from django.shortcuts import render, redirect

from music_app.album.models import Album
from music_app.profiles.models import Profile
from music_app.web.forms import CreateProfileForm


# Create your views here.
def get_profile():
    return Profile.objects.first()


def create_profile(request):
    form = CreateProfileForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('index')
    context = {
        "form": form,
        "no_nav": True,
    }
    return render(request, 'web/home-no-profile.html', context)


def index(request):
    if get_profile() is None:
        return create_profile(request)
    context = {
        "albums": Album.objects.all()
    }

    return render(request, "web/home-with-profile.html", context)

music_app/templates/album/album-add.html
{% extends 'base.html' %}
{% block main_content %}
    <!-- Main Content -->
    <!--Create Page-->
    <section class="createPage">
        <form action="{% url 'add-album' %}" method="post">
            <fieldset>
                <legend>Add Album</legend>
                <div class="container">
                    {{ form }}
                    <!-- Button for Adding Album -->
                    <button class="add-album" type="submit">Add New Album</button>
                    {% csrf_token %}
                </div>
            </fieldset>

        </form>
    </section>
{% endblock %}

music_app/templates/album/album-delete.html
{% extends 'base.html' %}
{% block main_content %}

    <!-- Main Content -->

    <!--Delete Page-->
    <section class="editPage">
        <form action="{% url 'delete-album' pk=object.pk%}" method="post">
            <fieldset>
                <legend>Delete Album</legend>
                <div class="container">
                    <!-- Form for Deleting an Album -->
                    {{ form }}
                    <!-- Button for Deleting an Album -->
                    <button class="delete-album" type="submit">Delete Album</button>
                    {% csrf_token %}
                </div>
            </fieldset>
        </form>
    </section>
    
{% endblock %}

music_app/templates/album/album-details.html
{% extends 'base.html' %}

{% block main_content %}
    <!-- Main Content -->
    <!--Details Page-->
    <section id="detailsPage">
        <div class="wrapper">
            <div class="albumCover">
                <!-- Album Image -->
                <img src="{{ object.image_url }}" alt="Cover Image"/>
            </div>

            <div class="albumInfo">
                <div class="albumText">
                    <!-- Album Info -->
                    <h1>Name: {{ object.album_name }}</h1>
                    <h3>Artist: {{ object.artist }}</h3>
                    <h4>Genre: {{ object.genre }}</h4>
                    <h4>Price: $7.33</h4>
                    {% if object.description %}
                        <p>
                            {{ object.description }}
                        </p>
                    {% endif %}
                </div>

                <div class="actionBtn">
                    <!-- Album Buttons -->
                    <a href="{% url 'edit-album' pk=object.pk %}" class="edit">Edit</a>
                    <a href="{% url 'delete-album' pk=object.pk %}" class="remove">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

music_app/templates/album/album-edit.html
{% extends 'base.html' %}
{% block main_content %}
    <!-- Main Content -->
    <!--Edit Page-->
    <section class="editPage">
        <form action="{% url 'edit-album' pk=object.pk %}" method="post">
            <fieldset>
                <legend>Edit Album</legend>
                <div class="container">
                    <!-- Form for Editing Album -->
                    {{ form }}
                    <!-- Button for Editing Album -->
                    <button class="edit-album" type="submit">Edit Album</button>
                    {% csrf_token %}
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

music_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>

<body>
<div id="box">
    <!-- Navigation Bar -->
    <header>
        <nav>
            <img src="{% static 'images/headphones.png' %}" alt="headphones"/>
            <a href="{% url 'index' %}">Home</a>
            {% if no_nav %}


                <ul></ul>
            {% else %}
                <ul>
                    <!--Only for user with created profile-->
                    <li><a href="{% url 'add-album' %}">Create Album</a></li>
                    <li><a href="{% url 'profile-details' %}">Profile</a></li>
                </ul>
            {% endif %}
        </nav>
    </header>
    <!-- End Navigation Bar -->
    {% block main_content %}

    {% endblock %}
    <!-- Footer -->
    <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
    </footer>
    <!-- End Footer -->
</div>
</body>
</html>

music_app/templates/profile/profile-delete.html
{% extends 'base.html' %}
{% block main_content %}
	
      <!-- Main Content -->
      <!-- Delete Profile Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profileText">
            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form action="{% url 'profile-delete' %}" method="post">
              <!-- Confirm Button -->
              <button class="delete-profile" type="submit">Delete</button>
                {% csrf_token %}
            </form>
            <!-- End Delete Profile Form -->
          </div>
        </div>
      </section>
{% endblock %}

music_app/templates/profile/profile-details.html
{% extends 'base.html' %}
{% block main_content %}

    <!-- Main Content -->
    <!--Details Page-->
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profilePage">
                <img
                        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                        alt="Profile Image"
                />
            </div>

            <div class="profileText">
                <!-- Profile Info -->
                <h1>Username: {{ object.username }}</h1>
                <h1>Email: {{ object.email }}</h1>
                {% if object.age %}
                <h1>Age: {{ object.age }}</h1>
                {% endif %}
                <h1>Albums: {{ object.album_set.count }}</h1>
            </div>

            <div class="actionBtn">
                <!-- Button for Deleting the Profile -->
                <a href="{% url 'profile-delete' %}" class="remove">Delete</a>
            </div>
        </div>
    </section>
    
{% endblock %}

music_app/templates/web/home-no-profile.html
{% load static %}
{% include 'base.html' %}

{% block main_content %}



    <!-- Main Content -->
    <!--Home Page-->
    <div class="container-inline">
        <section id="welcomePage">
            <div id="welcome-message">
                <h1>Welcome to</h1>
                <h1>My Music App!</h1>
            </div>
            <div class="music-img">
                <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon"/>
            </div>
        </section>

        <!-- Registration -->
        <section id="registerPage">
            <form action="{% url 'create_profile' %}" method="post">
                <fieldset>
                    <legend>Profile</legend>
                    <!-- Form for Registration -->
                {{ form }}
                    
{#                    <label for="username">Username:</label>#}
{#                    <input#}
{#                            id="username"#}
{#                            name="username"#}
{#                            type="text"#}
{#                            placeholder="Username"#}
{#                    />#}
{##}
{#                    <label for="email">Email:</label>#}
{#                    <input id="email" name="email" type="email" placeholder="Email"/>#}
{##}
{#                    <label for="age">Age:</label>#}
{#                    <input#}
{#                            id="age"#}
{#                            name="age"#}
{#                            type="number"#}
{#                            min="0"#}
{#                            placeholder="Age"#}
{#                    />#}
                    <!-- Button to Create Profile -->
                    <button type="submit" class="register">Enter</button>
                    {% csrf_token %}
                </fieldset>
            </form>
        </section>
    </div>

{% endblock %}

music_app/templates/web/home-with-profile.html
{% extends 'base.html' %}
{% block main_content %}

    <!-- Main Content -->
    <!-- Catalog with Albums-->
    <section id="catalogPage">
        {% if not albums %}
            <!--  If No albums in catalog -->
            <p>No Albums in Catalog!</p>
        {% else %}
            <!-- If albums in catalog -->
            <h1>All Albums</h1>
            {% for album in albums %}
                <!-- Card-Box in catalog -->
                <div class="card-box">
                    <img src="{{ album.image_url }}" alt="Cover Image"/>
                    <div>
                        <div class="text-center">
                            <p class="name">Name: {{ album.album_name }}</p>
                            <p class="artist">Artist: {{ album.artist }}</p>
                            <p class="genre">Genre: {{ album.genre }}</p>
                            <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
                        </div>
                        <div class="btn-group">
                            <a href="{% url 'details-album' pk=album.pk %}">Details</a>
                        </div>
                    </div>
                </div>
                <!-- Card-Box in catalog -->
            {% endfor %}


        {% endif %}
    </section>

{% endblock %}